name: Probe callee

on:
  workflow_call:

permissions:
  contents: write

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout probe
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Echo
        run: echo "probe ok"